In [4]:
with open('wiki_infobox_person.txt', 'r') as f:
    lines = f.readlines()

In [5]:
lines

['Religious person\n',
 '    Template:Infobox Buddha (Transclusion count: 21)\n',
 '    Template:Infobox Christian leader (Transclusion count: 11,129)\n',
 '    Template:Infobox clergy (Transclusion count: 615)\n',
 '    Template:Infobox Jewish leader (Transclusion count: 459)\n',
 '    Template:Infobox Latter Day Saint biography (Transclusion count: 675)\n',
 '    Template:Infobox rebbe (Transclusion count: 96)\n',
 '    Template:Infobox religious biography (Transclusion count: 1,707)\n',
 '    Template:Infobox saint (Transclusion count: 3,805)\n',
 'Royalty and nobility\n',
 '    Template:Infobox Egyptian dignitary (Transclusion count: 198)\n',
 '    Template:Infobox noble (Transclusion count: 4,895)\n',
 '    Template:Infobox peer (Transclusion count: 435)\n',
 '    Template:Infobox pharaoh (Transclusion count: 371)\n',
 '    Template:Infobox pretender (Transclusion count: 27)\n',
 '    Template:Infobox royalty (Transclusion count: 14,801)\n',
 'Sportsperson\n',
 '    American football person\n',
 '        Template:Infobox college football player (Transclusion count: 1,412)\n',
 '        Template:Infobox CFL biography (Transclusion count: 6,504)\n',
 '        Template:Infobox NFL biography (Transclusion count: 19,962)\n',
 '    Baseball person\n',
 '        Template:Infobox baseball biography (Transclusion count: 22,036)\n',
 '    Basketball person\n',
 '        Template:Infobox basketball biography (Transclusion count: 23,048)\n',
 '    Motorsports person\n',
 '        Template:Infobox Champ Car driver (Transclusion count: 121)\n',
 '        Template:Infobox F1 driver (Transclusion count: 903)\n',
 '        Template:Infobox Le Mans driver (Transclusion count: 392)\n',
 '        Template:Infobox Motocross rider (Transclusion count: 117)\n',
 '        Template:Infobox motorcycle rider (Transclusion count: 1,327)\n',
 '        Template:Infobox NASCAR driver (Transclusion count: 1,162)\n',
 '        Template:Infobox racing driver (Transclusion count: 2,457)\n',
 '        Template:Infobox racing driver series section (Transclusion count: 1,236)\n',
 '        Template:Infobox speedway rider (Transclusion count: 744)\n',
 '        Template:Infobox WRC driver (Transclusion count: 301)\n',
 '    Other sportsperson\n',
 '        Template:Infobox sportsperson (Transclusion count: 52,256)\n',
 '            Wrappers\n',
 '                Template:Infobox biathlete (Transclusion count: 231)\n',
 '                Template:Infobox boxer (amateur) (Transclusion count: 441)\n',
 '                Template:Infobox climber (Transclusion count: 145)\n',
 '                Template:Infobox professional bowler (Transclusion count: 25)\n',
 '                Template:Infobox sailor (Transclusion count: 859)\n',
 '                Template:Infobox speed skater (Transclusion count: 565)\n',
 '                Template:Infobox sport wrestler (Transclusion count: 175)\n',
 '                Template:Infobox swimmer (Transclusion count: 7,875)\n',
 '            Modules\n',
 '                Template:Infobox bullfighting career (Transclusion count: 12)\n',
 '        Template:Infobox AFL biography (Transclusion count: 13,238)\n',
 '        Template:Infobox alpine ski racer (Transclusion count: 514)\n',
 '        Template:Infobox amateur wrestler (Transclusion count: 453)\n',
 '        Template:Infobox badminton player (Transclusion count: 2,131)\n',
 '        Template:Infobox bandy biography (Transclusion count: 27)\n',
 '        Template:Infobox bodybuilder (Transclusion count: 303)\n',
 '        Template:Infobox boxer (Transclusion count: 4,300)\n',
 '        Template:Infobox cricketer (Transclusion count: 22,455)\n',
 '        Template:Infobox curler (Transclusion count: 831)\n',
 '        Template:Infobox cyclist (Transclusion count: 12,209)\n',
 '        Template:Infobox equestrian (Transclusion count: 160)\n',
 '        Template:Infobox fencer (Transclusion count: 459)\n',
 '        Template:Infobox field hockey player (Transclusion count: 359)\n',
 '        Template:Infobox figure skater (Transclusion count: 3,577)\n',
 '        Template:Infobox football biography (Transclusion count: 149,852)\n',
 '        Template:Infobox football official (Transclusion count: 753)\n',
 '        Template:Infobox Gaelic Athletic Association player (Transclusion count: 3,832)\n',
 '        Template:Infobox golfer (Transclusion count: 3,461)\n',
 '        Template:Infobox gymnast (Transclusion count: 2,461)\n',
 '        Template:Infobox handball biography (Transclusion count: 3,077)\n',
 '        Template:Infobox horseracing personality (Transclusion count: 913)\n',
 '        Template:Infobox ice hockey player (Transclusion count: 15,885)\n',
 '        Template:Infobox lacrosse player (Transclusion count: 438)\n',
 '        Template:Infobox martial artist (Transclusion count: 4,040)\n',
 '        Template:Infobox mountaineer (Transclusion count: 46)\n',
 '        Template:Infobox NCAA athlete (Transclusion count: 208)\n',
 '        Template:Infobox netball biography (Transclusion count: 275)\n',
 '        Template:Infobox National Hockey League coach (Transclusion count: 46)\n',
 '        Template:Infobox pelotari (Transclusion count: 16)\n',
 '        Template:Infobox professional wrestler (Transclusion count: 3,504)\n',
 '        Template:Infobox rugby biography (Transclusion count: 10,632) Holding cell\n',
 '        Template:Infobox rugby league biography (Transclusion count: 7,056) Holding cell\n',
 '        Template:Infobox skier (Transclusion count: 1,647)\n',
 '        Template:Infobox sports announcer details (Transclusion count: 93)\n',
 '        Template:Infobox squash player (Transclusion count: 440)\n',
 '        Template:Infobox sumo wrestler (Transclusion count: 500)\n',
 '        Template:Infobox surfer (Transclusion count: 178)\n',
 '        Template:Infobox table tennis player (Transclusion count: 588)\n',
 '        Template:Infobox tennis biography (Transclusion count: 5,912)\n',
 '        Template:Infobox volleyball biography (Transclusion count: 4,551)\n',
 'Other person\n',
 '    Template:Infobox person (Transclusion count: 290,129)\n',
 '        Template:Infobox academic (Transclusion count: 2,071)\n',
 '        Template:Infobox architect (Transclusion count: 2,419)\n',
 '        Template:Infobox artist (Transclusion count: 17,354)\n',
 '        Template:Infobox chef (Transclusion count: 699)\n',
 '        Template:Infobox clergy (Transclusion count: 615)\n',
 '        Template:Infobox classical composer (Transclusion count: 169)\n',
 '        Template:Infobox criminal (Transclusion count: 2,901)\n',
 '        Template:Infobox dancer (Transclusion count: 335)\n',
 '        Template:Infobox economist (Transclusion count: 1,468)\n',
 '        Template:Infobox engineer (Transclusion count: 847)\n',
 '            Template:Infobox engineering career (Transclusion count: 932)\n',
 '        Template:Infobox medical details (Transclusion count: 778)\n',
 '        Template:Infobox medical person (Transclusion count: 686)\n',
 '        Template:Infobox model (Transclusion count: 2,060)\n',
 '        Template:Infobox pageant titleholder (Transclusion count: 2,547)\n',
 '        Template:Infobox philosopher (Transclusion count: 2,293)\n',
 '        Template:Infobox pirate (Transclusion count: 154)\n',
 '        Template:Infobox police officer (Transclusion count: 398)\n',
 '        Template:Infobox presenter (Transclusion count: 601)\n',
 '        Template:Infobox scientist (Transclusion count: 28,453)\n',
 '        Template:Infobox sports announcer (Transclusion count: 61)\n',
 '        Template:Infobox spy (Transclusion count: 184)\n',
 '        Template:Infobox theologian (Transclusion count: 177)\n',
 '            Template:Infobox theological work (Transclusion count: 177)\n',
 '    Template:Infobox astronaut (Transclusion count: 706)\n',
 '    Template:Infobox aviator (Transclusion count: 234)\n',
 '    Template:Infobox chess biography (Transclusion count: 1,671)\n',
 '    Template:Infobox college coach (Transclusion count: 7,659)\n',
 '    Template:Infobox comedian (Transclusion count: 1,696)\n',
 '    Template:Infobox comics creator (Transclusion count: 3,042)\n',
 '    Template:Infobox darts player (Transclusion count: 701)\n',
 '    Template:Infobox FBI Ten Most Wanted (Transclusion count: 82)\n',
 '    Template:Infobox go player (Transclusion count: 243)\n',
 '    Template:Infobox gunpowder plotter (Transclusion count: 15)\n',
 '    Template:Infobox Magic: The Gathering player (Transclusion count: 104)\n',
 '    Template:Infobox member of the Knesset (Transclusion count: 941)\n',
 '    Template:Infobox military person (Transclusion count: 31,618)\n',
 '    Template:Infobox musical artist (Transclusion count: 99,555)\n',
 '    Template:Infobox Nahua officeholder (Transclusion count: 25)\n',
 '    Template:Infobox officeholder (Transclusion count: 120,827)\n',
 '        Template:Infobox Native American leader (Transclusion count: 249)\n',
 '    Template:Infobox Playboy Playmate (Transclusion count: 311)\n',
 '    Template:Infobox poker player (Transclusion count: 713)\n',
 '    Template:Infobox snooker player (Transclusion count: 562)\n',
 '    Template:Infobox video game player (Transclusion count: 305)\n',
 '    Template:Infobox War on Terror detainee (Transclusion count: 385)\n',
 '    Template:Infobox writer (Transclusion count: 26,788)\n',
 '    Template:Infobox YouTube personality (Transclusion count: 521)']

In [6]:
import re
import pandas as pd

In [62]:
def clean_line(l):
    return re.sub(' \(Transclusion count: [0-9,]+\)( Holding cell|)', '', l).strip().replace('Template:', '')
def get_count(l):
    return int(re.search('[0-9,]+', l)[0].replace(',', ''))

In [101]:
lst_infobox = []
belongs = ['', '', '', '', '']
for l in lines:
    cl = clean_line(l)
#     if len(re.findall(' {4}', l)) == 0:
#         belongs[0] == cl
#     elif len(re.findall(' {4}', l)) == 1:
#         belongs[1] == cl
#     elif len(re.findall(' {4}', l)) == 2:
#         belongs[2] == cl
#     elif len(re.findall(' {4}', l)) == 3:
#         belongs[3] == cl
    belongs[len(re.findall(' {4}', l))] = cl
    if re.search('Template:Infobox ', l) is not None:
        info = [cl, get_count(l)] + belongs
        info = info[:info[1:].index(info[0]) + 1]
        lst_infobox.append(info)

In [102]:
df_infobox = pd.DataFrame(lst_infobox, columns=['infobox_type', 'count', 'belong_to_1', 'belong_to_2', 'belong_to_3', 'belong_to_4'])

In [103]:
df_infobox.to_csv('infobox.csv', sep=',', index=False)

In [104]:
df_infobox.head(20)

,infobox_type,count,belong_to_1,belong_to_2,belong_to_3,belong_to_4
0,Infobox Buddha,21,Religious person,None,None,None
1,Infobox Christian leader,11129,Religious person,None,None,None
2,Infobox clergy,615,Religious person,None,None,None
3,Infobox Jewish leader,459,Religious person,None,None,None
4,Infobox Latter Day Saint biography,675,Religious person,None,None,None
5,Infobox rebbe,96,Religious person,None,None,None
6,Infobox religious biography,1707,Religious person,None,None,None
7,Infobox saint,3805,Religious person,None,None,None
8,Infobox Egyptian dignitary,198,Royalty and nobility,None,None,None
9,Infobox noble,4895,Royalty and nobility,None,None,None
10,Infobox peer,435,Royalty and nobility,None,None,None
11,Infobox pharaoh,371,Royalty and nobility,None,None,None
12,Infobox pretender,27,Royalty and nobility,None,None,None
13,Infobox royalty,14801,Royalty and nobility,None,None,None
14,Infobox college football player,1412,Sportsperson,American football person,None,None
15,Infobox CFL biography,6504,Sportsperson,American football person,None,None
16,Infobox NFL biography,19962,Sportsperson,American football person,None,None
17,Infobox baseball biography,22036,Sportsperson,Baseball person,None,None
18,Infobox basketball biography,23048,Sportsperson,Basketball person,None,None
19,Infobox Champ Car driver,121,Sportsperson,Motorsports person,None,None